### ISSUE TITLE
Submit to `github.com/microsoft/winget-pkgs`.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [Toxblh/WinToLinux#11]
#### **Advantages**

Provides automatic updates to users whilst allowing you to continue using GitHub Releases and CI.

#### **Achievement**

You'll want to request it at https://github.com/microsoft/winget-pkgs/issues/new?assignees=&labels=Help-Wanted%2CPackage-Request&projects=&template=package_request.yml&title=%5BPackage+Request%5D%3A+.

https://www.virustotal.com/gui/url/c29e7218d45388c0e39ea13da3e8680aee2d33e385626bcd9761ad649f18f7b1?nocache=1 doesn't indicate anything, so it should be trivial.

**Comment by Toxblh** [comment]
https://github.com/microsoft/winget-pkgs/issues/171308
