### ISSUE TITLE
doesn't work with ubuntu.

### ISSUE THREAD

**Issue by SuperMarioYAHOOYAHOO** [Toxblh/WinToLinux#5]
it just brings me to grub...

**Comment by Toxblh** [comment]
um.. but what should be? So Ubuntu use grub as init program. 
The program just to change you boot order of option, same like if you do it via F8 (usually, boot options in load stage)
If you bring grub and that don't expected - I can guess you choose not UEFI version and load in "legacy" version of start, choose another target

**Comment by SuperMarioYAHOOYAHOO** [comment]
> um.. but what should be? So Ubuntu use grub as init program. The program just to change you boot order of option, same like if you do it via F8 (usually, boot options in load stage) If you bring grub and that don't expected - I can guess you choose not UEFI version and load in "legacy" version of start, choose another target

what

**Comment by Toxblh** [comment]
What is problem? Grub is correct target for ubuntu

**Comment by Toxblh** [comment]
The app only change UEFI boot order and it's all.
